[package]

name = "nickel"
version = "0.7.2"
authors = [ "Christoph Burgdorf <christoph@thoughtram.io>",
            "Kevin Butler <haqkrs@gmail.com>",
            "Simon Persson <simon@flaskpost.org>" ]
description = "An express.js inspired web framework"
license = "MIT"

repository = "https://github.com/nickel-org/nickel.rs"
readme = "README.md"
keywords = ["nickel", "server", "web", "express"]

[features]
unstable = ["hyper/nightly", "compiletest_rs"]
ssl = ["hyper/ssl"]
timeouts = ["hyper/timeouts"]
default = ["timeouts"]

[dependencies]
url = "*"
time = "*"
typemap = "*"
plugin = "*"
regex = "*"
rustc-serialize = "*"
log = "*"
groupable = "*"
mustache = "*"
lazy_static = "*"
modifier = "*"

[dependencies.hyper]
version = "=0.6"
default-features = false

[dependencies.compiletest_rs]
version = "*"
optional = true

[[example]]

name = "example"
path = "examples/example.rs"

[[example]]

name = "example_with_default_router"
path = "examples/example_with_default_router.rs"

[[example]]

name = "example_template"
path = "examples/example_template.rs"

[[example]]

name = "macro_example"
path = "examples/macro_example.rs"

[[example]]

name = "hello_world"
path = "examples/hello_world.rs"

[[example]]

name = "hello_world_macro"
path = "examples/hello_world_macro.rs"

[[example]]

name = "moved_ownership"
path = "examples/moved_ownership.rs"

[[example]]

name = "example_route_data"
path = "examples/example_route_data.rs"

[[example]]

name = "mount"
path = "examples/mount.rs"

[[example]]

name = "chaining"
path = "examples/chaining.rs"

[[example]]

name = "form_data"
path = "examples/form_data/form_data.rs"
